language: csharp
dotnet: 6.0.400
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install 18.11.0
  - nvm use 18.11.0

script:
  - dotnet tool restore
  - npm install
  - npm run build:demo
  - npm test