init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "10.10.0"

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet core 3 preview
  # - cmd: choco install dotnetcore-sdk --pre
  - cmd: dotnet tool install -g fake-cli
  - cmd: dotnet tool install -g paket
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # # Update npm
  # # There seems to be issues with npm 5.4 in Windows
  # # See https://github.com/npm/npm/issues/18380
  # - npm install -g npm@6.1.0

os: Visual Studio 2022

build_script:
  - cmd: fake build -t test

test: off