init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

environment:
  nodejs_version: "18.11.0"

cache:
 - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # install latest dotnet core 3 preview
  - cmd: choco install dotnetcore-sdk --pre
  - cmd: dotnet tool restore
  - cmd: npm install
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version

os: Visual Studio 2019

build_script:
  - cmd: npm test

test: off